blank_issues_enabled: true
contact_links:
  - name: The Pants Documentation Site
    url: https://www.pantsbuild.org/
    about: You can find a lot of useful information here.
  - name: The Pants Community
    url: https://www.pantsbuild.org/docs/getting-help
    about: We're happy to answer questions on chat!
